# Generated by Django 2.1.10 on 2019-07-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_check', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tmp',
        ),
    ]
